### ISSUE TITLE
Where's the infrastructure?

### ISSUE THREAD

**Issue by pydanny** [rewardz/django_model_helpers#7]
- How are builds and distributions generated?
- Are there tests?
- Are there formal git tags?

**Comment by ramast** [comment]
> How are builds and distributions generated?

The library is a single file. It's built manually and published on pypi.
Can be installed using `pip install django-model-helpers`

> Are there formal git tags?

Not at the moment because when project started it was only used by rewardz. Now it's being used by others but no new features has been added so no tags were introduced yet.

> Are there tests?

Yes, in the "tests" directory with instructions on [how to run](https://github.com/rewardz/django_model_helpers/blob/master/tests/how_to_run.txt)

**Comment by ramast** [comment]
Tag has been added for current stable version v1.3
